### ISSUE TITLE
receive emails

### ISSUE THREAD

**Issue by sachinbhutani** [dac-gmbh/new-tokio-smtp#3]
is it possible to receive emails using new-tokio-smtp ? 
please add an example if possible on how to do it.

**Comment by rustonaut** [comment]
Sorry for the very late response.

Currently this library only supports a SMTP client, not a server.

Due to the SMTP protocol being asymmetric there is just a little bit of code which can be re-used by an server and there are a lot of additional thinks you would want to handle (like some DOS protection etc.).

So if I add smtp server capabilities it will not be anytime soon.
